modLoader="javafml" #mandatory
	
loaderVersion="[38,)" #mandatory 

license="All rights reserved"

[[mods]] #mandatory
	
modId="xeconomy" #mandatory

version="${file.jarVersion}" #mandatory

displayName="XEconomy Economy" #mandatory

logoFile="" #optional

credits="Thanks for downloading my Mod" #optional
	
authors="Luis" #optional

description='''
XEconomy Economy adds an Item Economy
Have a lot of fun when playing
XEconomy Development Team
'''
	
[[dependencies.xeconomy]] #optional
	
    modId="forge" #mandatory
    
    mandatory=true #mandatory
    
    versionRange="[38,)" #mandatory
    
    ordering="NONE"
    
    side="BOTH"
    
[[dependencies.xeconomy]]
		
    modId="minecraft"
    
    mandatory=true

    versionRange="[1.18,1.19)"
    
    ordering="NONE"
    
    side="BOTH"